### ISSUE TITLE
Where i may download this extensions for my chrome?

### ISSUE THREAD

**Issue by Iaroslav59** [konijn/Bookmark-Commander#1]
Please tell me, where i may downaload this extensions for my chrome browser? Link in chrome store doesnt work( Please give me you beutiful extension)! Thank You!

**Comment by konijn** [comment]
It's on my todo list, I need to renew my dev license and create a new manifest.

**Comment by konijn** [comment]
Done!
https://chrome.google.com/webstore/detail/dblbfailhcgonbjofnmilkejmmoikojm/

**Comment by pobat** [comment]
installed the application. but it does not start. what am I doing wrong?

**Comment by konijn** [comment]
Greetings,

you are not doing anything wrong. It seems a number of new security
practices go against my coding practices.
I need to adjust my coding practices ;)

**Comment by konijn** [comment]
Fixed!!

make sure to download 1.3.3
